module.exports = [
    { type: 22, value: 'var', line: 1 },
    { type: 33, value: 'b', line: 1 },
    { type: 7, value: '=', line: 1 },
    { type: 42, value: '[', line: 1 },
    { type: 42, value: ']', line: 1 },
    { type: 8, value: ';', line: 1 },
    { type: 50, value: '\n', line: 1 },
    {
        type: 'ULANGI',
        value: 'ulangi(var a sebanyak 5 kali)',
        line: 2
    },
    { type: 11, value: '{', line: 2 },
    { type: 50, value: '\n', line: 2 },
    { type: 33, value: 'b', line: 3 },
    { type: 42, value: '[', line: 3 },
    { type: 33, value: 'a', line: 3 },
    { type: 42, value: ']', line: 3 },
    { type: 7, value: '=', line: 3 },
    { type: 29, value: 'readlineSync.question', line: 3 },
    { type: 9, value: '(', line: 3 },
    { type: 25, value: '`b[${a}] = `', line: 3 },
    { type: 10, value: ')', line: 3 },
    { type: 50, value: '\n', line: 3 },
    { type: 12, value: '}', line: 4 },
    { type: 50, value: '\n', line: 4 },
    { type: 50, value: '\n', line: 5 },
    { type: 26, value: 'console.log', line: 6 },
    { type: 9, value: '(', line: 6 },
    { type: 33, value: 'b', line: 6 },
    { type: 10, value: ')', line: 6 },
    { type: 8, value: ';', line: 6 },
    { type: 50, value: '\n', line: 6 },
    { type: 50, value: '\n', line: 7 },
    { type: 22, value: 'var', line: 8 },
    { type: 33, value: 'lanjut', line: 8 },
    { type: 7, value: '=', line: 8 },
    { type: 16, value: 'true', line: 8 },
    { type: 8, value: ';', line: 8 },
    { type: 50, value: '\n', line: 8 },
    { type: 50, value: '\n', line: 9 },
    { type: 27, value: 'while', line: 10 },
    { type: 9, value: '(', line: 10 },
    { type: 33, value: 'lanjut', line: 10 },
    { type: 10, value: ')', line: 10 },
    { type: 11, value: '{', line: 10 },
    { type: 50, value: '\n', line: 10 },
    { type: 26, value: 'console.log', line: 11 },
    { type: 9, value: '(', line: 11 },
    { type: 25, value: '"berlanjut..."', line: 11 },
    { type: 10, value: ')', line: 11 },
    { type: 8, value: ';', line: 11 },
    { type: 50, value: '\n', line: 11 },
    { type: 33, value: 'lanjut', line: 12 },
    { type: 7, value: '=', line: 12 },
    { type: 17, value: 'false', line: 12 },
    { type: 8, value: ';', line: 12 },
    { type: 50, value: '\n', line: 12 },
    { type: 22, value: 'var', line: 13 },
    { type: 33, value: 'jawaban', line: 13 },
    { type: 7, value: '=', line: 13 },
    { type: 29, value: 'readlineSync.question', line: 13 },
    { type: 9, value: '(', line: 13 },
    { type: 25, value: '"mau lanjut? (iya/tidak) "', line: 13 },
    { type: 10, value: ')', line: 13 },
    { type: 8, value: ';', line: 13 },
    { type: 50, value: '\n', line: 13 },
    { type: 14, value: 'if', line: 14 },
    { type: 9, value: '(', line: 14 },
    { type: 33, value: 'jawaban', line: 14 },
    { type: 13, value: '===', line: 14 },
    { type: 25, value: '"iya"', line: 14 },
    { type: 10, value: ')', line: 14 },
    { type: 11, value: '{', line: 14 },
    { type: 50, value: '\n', line: 14 },
    { type: 33, value: 'lanjut', line: 15 },
    { type: 7, value: '=', line: 15 },
    { type: 16, value: 'true', line: 15 },
    { type: 8, value: ';', line: 15 },
    { type: 50, value: '\n', line: 15 },
    { type: 12, value: '}', line: 16 },
    { type: 50, value: '\n', line: 16 },
    { type: 12, value: '}', line: 17 },
    { type: 50, value: '\n', line: 17 }
]
